### ISSUE TITLE
About  `pcds_tmp `and `pcds_ht `

### ISSUE THREAD

**Issue by iris0329** [huixiancheng/No-CPGNet#1]
Hi Huixian, 

Thank you for opening this repo.

When reading the code, in the file `datasets/data.py`,  
```python
    def form_seq(self, meta_list):
        fname_pcd, fname_label, pose_diff, _, _ = meta_list
        # load pcd
        pcds_tmp = np.fromfile(fname_pcd, dtype=np.float32).reshape((-1, 4))
        pcds_ht = utils.Trans(pcds_tmp, pose_diff)

        # load label
        pcds_label = np.fromfile(fname_label, dtype=np.uint32)
        pcds_label = pcds_label.reshape((-1))
        sem_label = pcds_label & 0xFFFF
        inst_label = pcds_label >> 16
```

Could you tell me what is the function of `pcds_ht = utils.Trans(pcds_tmp, pose_diff)`, cus I visualize the `pcds_tmp `and `pcds_ht `, but it seems like they are identical,

**Comment by huixiancheng** [comment]
Hi, this part of code it's simply from [SMVF](https://github.com/GangZhang842/SMVF/blob/fe556eb01f6837782cb4f44362ed0ff0a85206ea/datasets/data.py#L190-L207). In that case, they use pose to transform multi frame lidar.
For single-frame point clouds, it may be useless. But at the time, I was unsure of its impact on SICP so retained it.
https://github.com/huixiancheng/No-CPGNet/blob/3d933e483819dae5b8548c351da1d003c9549a70/datasets/data.py#L143-L145

**Comment by iris0329** [comment]
Ah, I see. Thanks a lot!
